### ISSUE TITLE
[QST] Rolling OLS calculation

### ISSUE THREAD

**Issue by jumana51** [rapidsai/gQuant#101]
**What is your question?**
Is the a rolling OLS calculation available in gQuant similar to Pyfinance `PandasRollingOLS`?

I have a need for the rolling calculation to be performed on a GroupBy object, where a given dataframe is grouped by dates and slope calculated on a rolling basis.

**Comment by yidong72** [comment]
We currently don't have the RollingOLS function implemented.  You are welcome to contribute and make a PR.

The cudf rolling function can take the user-defined functions

https://docs.rapids.ai/api/cudf/stable/guide-to-udfs.html

You can implement it by defining the regression function.
