### ISSUE TITLE
[BUG] cuIndicator.ipynb - Incorrect path to dataset

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/gQuant#13]
Hi,

It seems that the path to the datasets is incorrect at **cuIndicator.ipynb** notebook.

Currently, it is defined as follows:
`"path": "/Project/data/stocks/stock_price_hist.csv.gz"`   
                                
I think it should be:
`"path": "../data/stock_price_hist.csv.gz"`

Something similar is happening with the following dataset:
`"path": "/Project/data/stocks/security_master.csv.gz"`

Hope it helps!

Miguel

**Comment by yidong72** [comment]
Yes. it is a bug we need to fix.
Can you help with it? @miguelangel 
Maybe you can fix this with this [issue](https://github.com/rapidsai/gQuant/issues/14) together in one PR?

**Comment by miguelangel** [comment]
Sure thing! I'll deal with it.
