### ISSUE TITLE
[BUG] cuIndicator.ipynb - Runtime error in cell #3 - Missing file

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/gQuant#14]
Hi,

When running cuIndicator.ipynb notebook the following message is displayed in cell #3:  

`FileNotFoundError: File .cache/node_csvdata.hdf5 does not exist`

I would sugget to perform the following change to fix the issue described above:

```
action = "load" if os.path.isfile('./.cache/node_csvdata.hdf5') else "save"
df = run([node_csv, node_sort], ['node_sort'], {'node_csvdata': {action: True}})[0]
```

Hope it helps!

Regards,
Miguel

**Comment by yidong72** [comment]
Yes. we need to fix it.

**Comment by miguelangel** [comment]
I will take care of it.
