### ISSUE TITLE
[BUG] 04_portfolio_trade.ipynb - Number of filtered stocks differs from text

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/gQuant#23]
Hi,

In 04_portfolio_trade.ipynb sample notebook, it seems that the number of filtered stocks in strategy_cached (#1558), differs from what it is stated in the paragraph below (#4598).

![image](https://user-images.githubusercontent.com/26169771/62811366-b0f94b80-bb01-11e9-9136-600bbb39031e.png)

I think the text figure should be changed to match the computation.

Regards,
Miguel

**Comment by yidong72** [comment]
this was addressed in the workflow class [PR](https://github.com/rapidsai/gQuant/pull/22)
