### ISSUE TITLE
[FEA] csvStockLoader.py and stockNameLoader.py - Use cudf.read_csv() insteand of pandas.read_csv()

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/gQuant#24]
Hi,

I have noticed we are using `pandas.read_csv()` instead of `cudf.read_csv()` method.

I have run a quick performance test, and cuDF version is much faster.

![image](https://user-images.githubusercontent.com/26169771/62811992-2c5bfc80-bb04-11e9-8f32-0a44b70034cb.png)

Based on the above, I would suggest changing `pandas.read_csv()` method occurrences to `cudf.read_csv()`.

Hope it helps.

Miguel

**Comment by miguelangel** [comment]
One more thing,

I have unzipped `'./data/stock_price_hist.csv.gz'` file and performed the same test and the results are much better.

![image](https://user-images.githubusercontent.com/26169771/62812238-1ef34200-bb05-11e9-84b2-8ff4a0c8c145.png)

So, I would suggest to unzip it after running `download_data.sh` script, and then read with cudf the unzip versions of the files.

What do you think?

Miguel

**Comment by yidong72** [comment]
Fixed in the #92
