### ISSUE TITLE
[BUG] Dask computation fails with 0.8 build script

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/gQuant#28]
Hi,

After integrating with RAPIDS v0.8, it seems that dask computation is failing.

It can be reproduced in `04_portfolio_trade.ipynb` notebook.

Regards,
Miguel

**Comment by miguelangel** [comment]
Hi @yidong72,

Would you mind to have a look at this issue? You are more knowledgeable than me on this subject.

Thanks!

Regards,

Miguel

**Comment by yidong72** [comment]
Yes I can look into this.

**Comment by yidong72** [comment]
It is the problem with cudf_dask.groupby.mean method. 
I filed a [bug/issue](https://github.com/rapidsai/cudf/issues/2543) to the cudf project. It can be reproduced as 
```python
import numpy as np
import cudf
from dask_cuda import LocalCUDACluster
cluster = LocalCUDACluster()
from dask.distributed import Client
client = Client(cluster)

for i in range(100):
    np.random.seed(3)
    size = 100
    groups = 20
    df = cudf.DataFrame()
    df['asset'] = np.random.randint(1, groups, size)
    df['num'] = np.random.rand(size)
    cdf = dask_cudf.from_cudf(df, npartitions=16)
    gt = df.groupby('asset').mean()
    dm = cdf.groupby('asset').mean().compute().reset_index().sort_values('index')
    print('trail', i, (gt['num']-dm['num']).abs().max())
```
