### ISSUE TITLE
[FEA] Rename viz_graph() to viz(), save_taskgraph() to save()

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/gQuant#34]
Hi,

I was wondering if we might rename `TaskGraph.viz_graph()` method to `TaskGraph.viz()`?

IMO, it is redundant to specify what we are visualizing or saving, and it would also make it more consistent with other methods in that class, such us `build()` or `run`.

Please, let me know your thoughts about the above.

Regards,
Miguel

**Comment by yidong72** [comment]
viz_graph is not a good method name.  "create_networkx_graph" is close to what it is doing

**Comment by avolkov1** [comment]
Maybe `to_nxgraph`.

**Comment by yidong72** [comment]
yes. I like `to_nxgraph`

**Comment by avolkov1** [comment]
Maybe wrap the plotting functionality as well? Instead of:
```
task_graph = TaskGraph(task_spec_list)
draw(task_graph.viz_graph(), show='ipynb')
```

Have a method:
```
task_graph.draw_ipynb()
```

**Comment by miguelangel** [comment]
Hi Alex,

I like the idea, but I think we are mixing responsabilities if we add that method (we are already doing it with to_nxgraph).

Visualization and business logic shouldn't be in the same class.

**Comment by miguelangel** [comment]
What about also renaming `save_taskgraph()` to `save() `?

**Comment by yidong72** [comment]
I like @avolkov1's approach. the nxgraph is only used for visualization and no business logic is used in that lib

**Comment by miguelangel** [comment]
Just to make it sure, will we have two methods (`to_nxgraph` and `draw_ipynb`) or only one (`draw_ipynb`)?

**Comment by yidong72** [comment]
I would say only one draw_ipynb method.

**Comment by miguelangel** [comment]
> I like @avolkov1's approach. the nxgraph is only used for visualization and no business logic is used in that lib

Hi @yidong72 ,

I somehow disagree with you.

Imagine you are not coding using Jupyter notebooks, and you would like to visualize in your Unix terminal the graph (using ASCII art).

You would need to create a class to visualize it.

So half of the visualization methods (display in Jupyter notebooks) is in TaskGraph, while the other is in your new visualizaton class.

**Comment by miguelangel** [comment]
Imagine now that you would like to export to different files formats. You would need a different class.

In that scenario, we would have two classes (TaskGraphToAscii) and (TaskGraphToFile) but still a method inside TaskGraph to visualize in Jupyter notebook

**Comment by yidong72** [comment]
You are right. networkx graph can be drawn in different ways. I found this [document](https://networkx.github.io/documentation/stable/reference/drawing.html). Maybe we can do two methods. I don't have a strong opinion on this.

**Comment by miguelangel** [comment]
I’m fine with two methods.


> What about also renaming `save_taskgraph()` to `save() `?

**Comment by avolkov1** [comment]
I think having an nx graph representation would be useful in other scenarios besides plotting in notebooks.

Having a draw method could be generalized like `task_graph.draw(fmt='ipynb')` or `task_graph.draw(fmt='png', stream=some_stream)` where stream could be a StringIO or file handle.

Yea, makes sense to simplify `save_taskgraph` to save and correspondingly `load_taskgraph` to `load`. If it's a method of `TaskGraph` that implies it's saving or loading a task-graph.

**Comment by yidong72** [comment]
I agree with @avolkov1, let's do this.

**Comment by miguelangel** [comment]
[Alea iacta est!](https://en.m.wikipedia.org/wiki/Alea_iacta_est)

**Comment by yidong72** [comment]
close this for now
