### ISSUE TITLE
[FEA] Refactor 04_portfolio_trade.ipynb notebook

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/gQuant#39]
Hi,

I have made some changes to 04_portfolio_trade.ipynb notebook trying to make it easier to follow.

I hope you like it.

Miguel

**Comment by avolkov1** [comment]
Is there a link to the changes for `04_portfolio_trade.ipynb`, I don't see it? I saw the updates to `01_tutorial.ipynb` notebook in PR #36. Looks pretty good.

**Comment by miguelangel** [comment]
Hi!

I will submit the PR tonight

**Comment by miguelangel** [comment]
Fixed with PR https://github.com/rapidsai/gQuant/pull/44.
