### ISSUE TITLE
[DOC] Add CHANGELOG.md

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/gQuant#48]
## Report incorrect documentation

**Location of incorrect documentation**
It is missing a CHANGELOG.md file at the root of the project.

Please, add what you would like to be added in that file.

I will group all of them and generate a file similar to this:

https://github.com/rapidsai/cudf/blob/branch-0.10/CHANGELOG.md

It might be useful to have a look at this project for reference:

https://github.com/rapidsai/gQuant/projects/1

**Comment by avolkov1** [comment]
Fixed in PR #94 commit 5d53970.
