### ISSUE TITLE
[BUG] download_data.sh seems to do not be in containers anymore

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/gQuant#66]
**Describe the bug**
Most of the notebooks invokes, in the first cell, the `download_data.sh` script, to download the test dataset if needed. 

It seems that `download_data.sh` is not available anymore in the container.

**Steps/Code to reproduce bug**
Try to execute the first cell of the tutorial notebook.

**Expected behavior**
The test dataset should be downloaded.

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of gQuant install: [Docker build, or from source]

**Environment details**
Please run and paste the output of the `/print_env.sh` script here, to gather any other relevant environment details

**Additional context**

**Comment by jbaron** [comment]
I just submitted PR that contains also fix for this.

**Comment by yidong72** [comment]
close it
