### ISSUE TITLE
[FEA] Conda resolves too slow in the latest versions of the container

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/gQuant#67]
**Is your feature request related to a problem? Please describe.**
When building the container, it takes a long time to resolve conda dependencies.

I have found that issue before. It looks like we have, at any moment, introduced a dependency that makes conda to take a long time to resolve.

**Describe the solution you'd like**
Make it much faster.

**Additional context**
I will assign this issue to me because I have worked before in optimising that container.

**Comment by miguelangel** [comment]
Hi @yidong72 @avolkov1,

I am considering removing the following dependencies when building the container. I am not sure they should be included in a 'runtime' version of the container:
- recommonmark
- dask-labextension
- sphinx_rtd_theme
- pudb
- pytables

Please, let me know your thoughts about the above.

Regards,
Miguel

**Comment by avolkov1** [comment]
> Hi @yidong72 @avolkov1,
> 
> I am considering removing the following dependencies when building the container. I am not sure they should be included in a 'runtime' version of the container:
> 
> * recommonmark
> * dask-labextension
> * sphinx_rtd_theme
> * pudb
> * pytables
> 
> Please, let me know your thoughts about the above.
> 
> Regards,
> Miguel

Pytables is important. That's used for saving dataframes (cudf or pandas) to hdf5 files which is done during caching. The other stuff you could probably remove.

**Comment by Joseaestevez** [comment]
Hi @avolkov1, @yidong72,
Been running the build.sh for 11 hours straight.
Is the build script stuck?

Its a MSI GS65 with high end specs (12 HW threads, +2000 CUDA ) so I would not expect it to take this much time.

When looking at the system monitor I can see that it is working on 1 thread (100%).
And about every few minutes it switches thread.

When reading the "https://github.com/NVIDIA/nvidia-docker#quickstart",
one statement is saying that CUDA toolkid is included in Docker 19.03 and hence not needed.
IS this true, should it be installed separatly or will the docker be sufficient?
The the statement bellow:
"Make sure you have installed the NVIDIA driver and Docker 19.03 for your Linux distribution Note that you **do not need to install the CUDA toolkit** on the host, but the driver needs to be installed"


**- One thing to improve is multi threading when istalling dependencis?**


been stuck at the last row here for +10 hours:
`Building wheels for collected packages: gquant
  Building wheel for gquant (setup.py): started
  Building wheel for gquant (setup.py): finished with status 'done'
  Created wheel for gquant: filename=gquant-0.1-cp36-none-any.whl size=60454 sha256=71cd844f90ac5bf281a08272594338c433e334055c4aeb7f21e8a7d2dbd7d870
  Stored in directory: /tmp/pip-ephem-wheel-cache-451ujfw0/wheels/58/ac/35/4411ec2da81d3d1ea418586a9f40015d5e257f81d6bfb15d2e
Successfully built gquant
Installing collected packages: gquant
Successfully installed gquant-0.1
Removing intermediate container 3c8783bdefa5
 ---> 111e6a79375b
Step 8/15 : RUN source activate rapids     && conda install -y -c conda-forge dask-labextension recommonmark numpydoc sphinx_rtd_theme pudb     python-graphviz bqplot=0.11.5 nodejs=11.11.0 jupyterlab=0.35.4 ipywidgets=7.4.2 pytables mkl numexpr
 ---> Running in bc23085a7793
Collecting package metadata: ...working... done
Solving environment: ...working... `

Thanks for taking your time!
Is the Repo open for anyone to contribute? (just asking)

BR,

**Comment by yidong72** [comment]
@Joseaestevez, sorry to hear about your experience with building the image. There is some issue in conda trying to resolve the dependency. It takes me 20-30mins in a DGX machine to build it. Stuck for +10 hours is a little too much. @miguelangel is still actively working on this with the RAPIDS team. We are also considering put out a pre-build docker image for everyone to download. It is not worth the time for everyone to build it from scratch. 

This is an open-source project and we are welcome anyone to contribute.

**Comment by miguelangel** [comment]
Hi @Joseaestevez , I am working on a fix on this. I will let you know as soon as finished.

**Comment by miguelangel** [comment]
Hi @Joseaestevez , please find attached a new `build.sh` script.

Could you please try this script and let me know if it resolves the issue described above?

Thanks!

P.S.: The file has been zipped. It would need to be unzipped before using it.
[build.zip](https://github.com/rapidsai/gQuant/files/3855555/build.zip)

**Comment by miguelangel** [comment]
Hi @Joseaestevez ,

It looks that the file I added in the previous comment has been useful for another user with the same issue.

Have you given it a try? If it works for you, I will submit a PR to fix it in the master branch.

Thanks!

Regards,
Miguel

**Comment by yidong72** [comment]
It is fixed on the RAPIDS side. Close it for now
