### ISSUE TITLE
[QST] how long is the container building step would take ?

### ISSUE THREAD

**Issue by complyue** [rapidsai/gQuant#71]
Congratulations on your great achievement firstly!

however in trying it out, I've been stuck at

```console
Step 8/15 : RUN source activate rapids     && conda install -y -c conda-forge dask-labextension recommonmark numpydoc sphinx_rtd_theme pudb     python-graphviz bqplot=0.11.5 nodejs=11.11.0 jupyterlab=0.35.4 ipywidgets=7.4.2 pytables mkl numexpr
 ---> Running in aca38a804a3f
Collecting package metadata: ...working... done
Solving environment: ...working... 
```

for several hours. 

should it finally make it given I wait longer? (what's the expected time then?)

or what diagnostic steps to be taken?

sorry I'm not familiar with docker for now, but glad to learn it up with some pointers.

Thanks & Regards!

**Comment by miguelangel** [comment]
Hi,

It shouldn’t take more than 15/30 minutes, depending on your system.

I have created a patch for this issue, you can find it here.

https://github.com/rapidsai/gQuant/issues/67#issuecomment-554742124

Could you please give it a try and let us know if it works?

Thanks

**Comment by complyue** [comment]
@miguelangel it worked for me, thanks!
