### ISSUE TITLE
[QST] Docker enterprise edition required ?

### ISSUE THREAD

**Issue by complyue** [rapidsai/gQuant#72]
I'm on Ubuntu 18.04.3, does this mean I have to subscribe to docker-ee to install the correct version ?

```bash
$ sudo apt install -y nvidia-docker2=2.0.3+docker18.09.7-3 nvidia-docker2=2.0.3+docker18.09.7-3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nvidia-docker2 : Depends: nvidia-container-runtime (= 2.0.0+docker18.09.7-3) but 3.1.4-1 is to be installed
                  Depends: docker-ce (= 5:18.09.7~3-0~ubuntu-bionic) but 5:19.03.5~3-0~ubuntu-bionic is to be installed or
                           docker-ee (= 5:18.09.7~3-0~ubuntu-bionic) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Thanks!

**Comment by avolkov1** [comment]
No you don't need docker ee.

Which version of docker are you using? You might not need to install nvidia-docker2 at all if using docker19.03. The install instructions are here:
https://github.com/NVIDIA/nvidia-docker

Again note:
> Note that with the release of Docker 19.03, usage of nvidia-docker2 packages are deprecated since NVIDIA GPUs are now natively supported as devices in the Docker runtime.

Refer to examples for using latest docker.
https://docs.docker.com/config/containers/resource_constraints/#expose-gpus-for-use
https://github.com/NVIDIA/nvidia-docker#usage

If you are using docker prior to 19.03 then install nvidia-docker2 via instructions on git repo.
https://github.com/NVIDIA/nvidia-docker#ubuntu-16041804-debian-jessiestretchbuster

**Comment by complyue** [comment]
is the cmdl documented somewhere, to start gQuant notebook server with docker 19.03+? I have difficulty to figure out by myself for now.

**Comment by avolkov1** [comment]
First build the container.
```
# clone gquant repo
cd gQuant/docker && . build.sh
```
You might want to use the patched build script from here:
https://github.com/rapidsai/gQuant/issues/67#issuecomment-554742124

Default docker tag is `gquant/gquant:latest`.
Then launch an interactive docker container session. If using docker 19.03+ it would look like this:
```
docker run --gpus all --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 gquant/gquant:latest
```
If using nvidia-docker2 then like this:
```
docker run --runtime=nvidia --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 gquant/gquant:latest
```

Then start jupyter how you usually start it from within the interactive docker session. There should be a utility helper script in the container as well to start a jupyter session.
```
bash /rapids/notebooks/utils/start-jupyter.sh
```

The above commands are not comprehensive. You might want to mount/map volumes i.e. filesystem paths into the container (use `-v` option for docker), run as user (use `-u` option for docker), etc. Refer to docker documentation and/or a docker tutorial.

**Comment by complyue** [comment]
thanks, I've guessed the `--gpus all` cmdl, but encountered error, I thought that's bcoz incompatible with gQuant, so seems not that reason. please help to have a look at this error:

```bash
$ docker run --gpus all --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 gquant/gquant:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: cuda error: unknown error\\\\n\\\"\"": unknown.
$ docker --version
Docker version 19.03.5, build 633a0ea838
```

I'm testing on a laptop with an MX150:
```bash
$ nvidia-smi 
Wed Dec  4 14:28:56 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.36       Driver Version: 440.36       CUDA Version: ERR!     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce MX150       Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   37C    P8    N/A /  N/A |      0MiB /  2002MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

I installed nvidia-driver-440 by `ubuntu-driver install`, the pkgs:
```bash
$ apt list --installed | grep nvidia

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libnvidia-cfg1-440/bionic,now 440.36-0ubuntu0~0.18.04.1 amd64 [installed,automatic]
libnvidia-common-440/bionic,bionic,now 440.36-0ubuntu0~0.18.04.1 all [installed,automatic]
libnvidia-compute-440/bionic,now 440.36-0ubuntu0~0.18.04.1 amd64 [installed,automatic]
libnvidia-container-tools/bionic,now 1.0.5-1 amd64 [installed,automatic]
libnvidia-container1/bionic,now 1.0.5-1 amd64 [installed,automatic]
libnvidia-decode-440/bionic,now 440.36-0ubuntu0~0.18.04.1 amd64 [installed,automatic]
libnvidia-encode-440/bionic,now 440.36-0ubuntu0~0.18.04.1 amd64 [installed,automatic]
libnvidia-fbc1-440/bionic,now 440.36-0ubuntu0~0.18.04.1 amd64 [installed,automatic]
libnvidia-gl-440/bionic,now 440.36-0ubuntu0~0.18.04.1 amd64 [installed,automatic]
libnvidia-ifr1-440/bionic,now 440.36-0ubuntu0~0.18.04.1 amd64 [installed,automatic]
nvidia-compute-utils-440/bionic,now 440.36-0ubuntu0~0.18.04.1 amd64 [installed,automatic]
nvidia-container-runtime/bionic,now 3.1.4-1 amd64 [installed]
nvidia-container-toolkit/bionic,now 1.0.5-1 amd64 [installed]
nvidia-dkms-440/bionic,now 440.36-0ubuntu0~0.18.04.1 amd64 [installed,automatic]
nvidia-driver-440/bionic,now 440.36-0ubuntu0~0.18.04.1 amd64 [installed]
nvidia-kernel-common-440/bionic,now 440.36-0ubuntu0~0.18.04.1 amd64 [installed,automatic]
nvidia-kernel-source-440/bionic,now 440.36-0ubuntu0~0.18.04.1 amd64 [installed,automatic]
nvidia-prime/bionic-updates,bionic-updates,now 0.8.8.2 all [installed]
nvidia-settings/bionic,now 418.56-0ubuntu0~gpu18.04.1 amd64 [installed,automatic]
nvidia-utils-440/bionic,now 440.36-0ubuntu0~0.18.04.1 amd64 [installed,automatic]
xserver-xorg-video-nvidia-440/bionic,now 440.36-0ubuntu0~0.18.04.1 amd64 [installed,automatic]
```

And I use Wayland for desktop login, it doesn't support nvidia driver, leaving it available for compute only.

**Comment by complyue** [comment]
I roughly remember `nvidia-smi` shows `CUDA 10.2` instead of `CUDA Version: ERR!` before I allowed my ubuntu to update its kernel to 5.0. should nvidia driver generally works okay for 5.0 kernel? or should I rollback to an older kernel?

**Comment by avolkov1** [comment]
The cuda toolkit version in containers can differ from expected system cuda version. The latest drivers are released to support the latest CUDA toolkit, but the latest drivers also support most of the legacy CUDA toolkits as well. So if you have driver 440 that support toolkit 10.2, that driver also support 10.1, 10.0, 9.x, 8.x, etc. Nvidia puts out release notice if support for some toolkit version is dropped (I think version 5.x and below might not be supported anymore).

Could you verify that CUDA works on your system?

Did you reboot after installing drivers?
Can you install cudatoolkit and SDK samples and compile one of the utilities (the deviceQuery example would work) to check that CUDA driver works and you can run CUDA apps?

I personally have not used the default ubuntu repos. The driver in the default ubuntu repo might only be for display and not support CUDA.

You can try the following with ubuntu repos. Install the toolkit like this:
```
sudo apt install nvidia-cuda-toolkit
```

You can download the SDK samples here: https://github.com/NVIDIA/cuda-samples
```
cd cuda-samples/Samples/deviceQuery/
make
./deviceQuery
```

If the above doesn't work I would use nvidia repos cuda-drivers instead. Uninstall the ubuntu repos nvidia-drivers and use nvidia repos nvidia-drivers. Below are the instructions to use Nvidia repos for Ubuntu 18.
```
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.2.89-1_amd64.deb
```
Then follow instructions here:
https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#ubuntu-installation

Then try to re-compile and re-run the deviceQuery utility.

Once you can verify and run CUDA apps then try running docker containers with GPUs again.

**Comment by complyue** [comment]
I tried to revert my kernel to 4.18 but it won't start desktop, with latest 5.0 kernel, tried re-installing driver 440 with reboots, still no luck:
```bash
cyue@cyuembpx:/MassData/Cuda/cuda_10.1.243_418.87.00_linux/cuda-samples/1_Utilities/deviceQueryDrv$ ./deviceQueryDrv 
./deviceQueryDrv Starting...

CUDA Device Query (Driver API) statically linked version 
cuInit(0) returned -1
-> (null)
Result = FAIL
cyue@cyuembpx:/MassData/Cuda/cuda_10.1.243_418.87.00_linux/cuda-samples/1_Utilities/deviceQueryDrv$ lsmod | grep nvidia
nvidia_uvm            933888  0
nvidia_drm             49152  0
nvidia_modeset       1110016  1 nvidia_drm
nvidia              19898368  20 nvidia_uvm,nvidia_modeset
drm_kms_helper        180224  2 nvidia_drm,i915
drm                   483328  24 drm_kms_helper,nvidia_drm,i915
ipmi_msghandler       102400  2 ipmi_devintf,nvidia
cyue@cyuembpx:/MassData/Cuda/cuda_10.1.243_418.87.00_linux/cuda-samples/1_Utilities/deviceQueryDrv$ nvidia-smi 
Thu Dec  5 15:36:43 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.36       Driver Version: 440.36       CUDA Version: ERR!     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce MX150       Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   44C    P8    N/A /  N/A |      0MiB /  2002MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by avolkov1** [comment]
Are you using Nividia repo for the drivers?
https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64

Using the latest kernel should be fine I think.

**Comment by complyue** [comment]
how to use this repo? seems I'm using ubuntu's ppa, not from nvidia.

**Comment by avolkov1** [comment]
> how to use this repo? seems I'm using ubuntu's ppa, not from nvidia.

Uninstall nvidia packages/drivers that were installed from Ubuntu's ppa.
```
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.2.89-1_amd64.deb
sudo dpkg -i cuda-repo-ubuntu1804_10.2.89-1_amd64.deb
```
Follow instructions here:
https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#ubuntu-installation

**Comment by complyue** [comment]
this solved my problem, thanks very much
